### ISSUE TITLE
Error on processing ShapeNetCore

### ISSUE THREAD

**Issue by unknownue** [Regenerator/dpf-nets#2]
I tried to apply `preprocess_ShapeNetCore.py` to [ShapeNetCore v2](https://www.shapenet.org/download/shapenetcore), but encountered following error:
```
02958343/d92a10c4db3974e14e88eef43f41dc4/models/ does not exist!
02958343/6885092b0d1fbb6a8db35146c0a9b3fb/models/ does not exist!
02958343/92d0fa7147696cf5ba531e418cb6cd7d/models/ does not exist!
02958343/c7bf88ef123ed4221694f51f0d69b70d/models/ does not exist!
02958343/bd8d7b8ad35df2d52470de2774d6099/models/ does not exist!
02958343/8843d862a7545d0d96db382b382d7132/models/ does not exist!
02958343/8b68f086176443b8128fe65339f3ddb2/models/ does not exist!
02958343/9e75756bd1bb8ebaafe1d4530f4c6e24/models/ does not exist!
02958343/dc0601024a535f5c51894d116f1c652/models/ does not exist!
02958343/79bf4c4574bc9c4552470de2774d6099/models/ does not exist!
02958343/6d619fcbceaa0327104b57ee967e352c/models/ does not exist!
02958343/e3c1213d68656ffb065f1478754df44/models/ does not exist!
02958343/5aa136c67d0a2a2852470de2774d6099/models/ does not exist!
02958343/4253a9aac998848f664839bbd828e448/models/ does not exist!
02958343/a81cb450ce415d45bdb32c3dfd2f01b5/models/ does not exist!
02958343/917de64538fb9f3afe1d4530f4c6e24/models/ does not exist!
02958343/c099c763ee6e485052470de2774d6099/models/ does not exist!
02958343/f4e25d681ad736eb52470de2774d6099/models/ does not exist!
02958343/64998426e6d48ae358dbdf2b5c6acfca/models/ does not exist!
02958343/29a4e6ae1f9cecab52470de2774d6099/models/ does not exist!
02958343/c9991032ff77fe8552470de2774d6099/models/ does not exist!
02958343/de1800e9ce6da9af52470de2774d6099/models/ does not exist!
02958343/a18fd5cb2a9d01c4158fe40320a23c2/models/ does not exist!
02958343/a8dde04ca72c5bdd6ca2b6e5474aad11/models/ does not exist!
02958343/f59a474f2ec175eb7cdba8f50ac8d46c/models/ does not exist!
02958343/7ee6884bb0bbf9e352470de2774d6099/models/ does not exist!
02958343/79e32e66bbf04191afe1d4530f4c6e24/models/ does not exist!
02958343/642b3dcc3e34ae3bafe1d4530f4c6e24/models/ does not exist!
02958343/5b04b836924fe955dab8f5f5224d1d8a/models/ does not exist!
04379243/619a795a84e2566ac22e965981351403/models/ does not exist!
04379243/3dadf67ebe6c29a3d291861d5bc3e7c8/models/ does not exist!
04379243/19e2321df1141bf3b76e29c9c43bc7aa/models/ does not exist!
04379243/4ebb653961d95dd075c67b3b1e763fcf/models/ does not exist!
04379243/2ab4b8a3fe51d2ba1b17743c18fb63dc/models/ does not exist!
04379243/6a977967aedbb60048b9747b6b395fc5/models/ does not exist!
04379243/2b9b2ece245dffbaaa11adad6b2a69c/models/ does not exist!
04379243/5a935225ccc57f09e6a4ada36a392e0/models/ does not exist!
04379243/5a60822959b28856920de219c00d1c3b/models/ does not exist!
04379243/7cb09d16e07e1d757e1dc03b595bd36c/models/ does not exist!
04379243/1a46011ef7d2230785b479b317175b55/models/ does not exist!
04379243/7206545c3f0a3070e8058cf23f6382c1/models/ does not exist!
04379243/a5b0aa0232ecc6dbd2f1945599cd5176/models/ does not exist!
Packing train meshes: [1/2233]
Packing train meshes: [2/2233]
Packing train meshes: [3/2233]
...
```
and
```
Packing train meshes: [513/2233]
Packing train meshes: [514/2233]
Packing train meshes: [515/2233]
Packing train meshes: [516/2233]
Packing train meshes: [517/2233]
Packing train meshes: [518/2233]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "preprocess_ShapeNetCore.py", line 26, in process_obj_file
    sample_obj = ObjMesh(sample)
  File "/workspace/Experiment/dpf-nets/lib/meshes/objmesh.py", line 12, in __init__
    with open(self.obj_filename, 'r', encoding='utf-8') as objf:
FileNotFoundError: [Errno 2] No such file or directory: '../../Datasets/ShapeNetCore.v2/shapes/02958343/7aa9619e89baaec6d9b8dfa78596b717/models/model_normalized.obj'
"""
```
It seems that this obj does not exist on original dataset, see [here](http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v2/02958343/7aa9619e89baaec6d9b8dfa78596b717/models/).
Is there some action I have to take before processing the the ShapeNetCore v2 dataset ?

**Comment by Regenerator** [comment]
Thanks for reporting this issue.

There are mistakes in both dataset and the official split. Some of the shape directories which are mentioned in the split do not exist in the dataset (as in the first set of errors), for other shapes paths to files do not correspond to what is described on the dataset page, sometimes the files just do not exist in the dataset (as in the second error). 

In my version of the dataset, I manually corrected some of these issues.
However, here for convenience I updated the preprocessing script to check if `./ShapeNetCore.v2/shapes/synsetID/modelID/models/model_normalized.obj` exists before including the shape in the preprocessing list. If something does not exist, it is not included in the hdf5 repacked version of the dataset.

Please, do report such cases if you encounter more of them, I will try to work around all of them without modifying the dataset.

**Comment by unknownue** [comment]
Ok, ShapeNetCore v2 now can be processed without triggering any error, and the code does run. In the nearly future, I may try processing ShapeNetAll13.
